server {
    listen 443 ssl;
    http2 on;
    server_name  botz.ai www.botz.ai localhost;

    location / {
        root   /usr/share/nginx/html/botz.ai;
        index  index.html index.htm;
    }

    location /editorials {
        proxy_set_header Host $host;
        proxy_read_timeout 900s;
        proxy_connect_timeout 75s;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass http://botz:3000;
    }

    location /archive {
        proxy_set_header Host $host;
        proxy_read_timeout 900s;
        proxy_connect_timeout 75s;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass http://botz:3000;
    }

    error_page 400 401 402 403 404 405 406 407 408 409 410 411 412 413 414 415 416 417 418 421 422 423 424 425 /error.html;

    location /error.html {
      ssi on;
      internal;
      auth_basic off;
      root /usr/share/nginx/html;
    }
}
